# Auto-generated file. Do not edit manually.

ZAMBIA_CONSTITUENCIES = {
    "Central": [
        "Bwacha",
        "Chisamba",
        "Chitambo",
        "Itezhi-Tezhi",
        "Kabwe Central",
        "Kapiri Mposhi",
        "Katuba",
        "Keembe",
        "Lufubu",
        "Mkushi North",
        "Mkushi South",
        "Muchinga",
        "Mumbwa",
        "Mwembeshi",
        "Nangoma",
        "Serenje",
    ],
    "Copperbelt": [
        "Bwana Mkubwa",
        "Chifubu",
        "Chililabombwe",
        "Chimwemwe",
        "Chingola",
        "Kabushi",
        "Kafulafuta",
        "Kalulushi",
        "Kamfinsa",
        "Kankoyo",
        "Kantanshi",
        "Kwacha",
        "Luanshya",
        "Lufwanyama",
        "Masaiti",
        "Mpongwe",
        "Mufulira",
        "Nchanga",
        "Ndola Central",
        "Nkana",
        "Roan",
        "Wusakile",
    ],
    "Eastern": [
        "Chadiza",
        "Chasefu",
        "Chipangali",
        "Chipata Central",
        "Kapoche",
        "Kasenengwa",
        "Kaumbwe",
        "Luangeni",
        "Lumezi",
        "Lundazi",
        "Malambo",
        "Milanzi",
        "Mkaika",
        "Msanzala",
        "Nyimba",
        "Petauke Central",
        "Sinda",
        "Vubwi",
    ],
    "Luapula": [
        "Bahati",
        "Bangweulu",
        "Chembe",
        "Chienge",
        "Chifunabuli",
        "Chipili",
        "Kawambwa",
        "Luapula",
        "Mambilima",
        "Mansa Central",
        "Milenge",
        "Mwansabombwe",
        "Mwense",
        "Nchelenge",
        "Pambashe",
    ],
    "Lusaka": [
        "Chawama",
        "Chilanga",
        "Chirundu",
        "Chongwe",
        "Feira",
        "Kabwata",
        "Kafue",
        "Kanyama",
        "Lusaka Central",
        "Mandevu",
        "Matero",
        "Munali",
        "Rufunsa",
    ],
    "Muchinga": [
        "Chama North",
        "Chama South",
        "Chinsali",
        "Isoka",
        "Kanchibiya",
        "Mafinga",
        "Mfuwe",
        "Mpika",
        "Nakonde",
        "Shiwa Ng'andu",
    ],
    "North-Western": [
        "Chavuma",
        "Ikeleng'i",
        "Kabompo",
        "Kasempa",
        "Manyinga",
        "Mufumbwe",
        "Mwinilunga",
        "Solwezi Central",
        "Solwezi East",
        "Solwezi West",
        "Zambezi East",
        "Zambezi West",
    ],
    "Northern": [
        "Chilubi",
        "Chimbamilonga",
        "Kaputa",
        "Kasama",
        "Lubansenshi",
        "Lukashya",
        "Lunte",
        "Lupososhi",
        "Malole",
        "Mbala",
        "Mporokoso",
        "Mpulungu",
        "Senga Hill",
    ],
    "Southern": [
        "Bweengwa",
        "Chikankata",
        "Choma",
        "Dundumwenzi",
        "Gwembe",
        "Kalomo Central",
        "Katombola",
        "Livingstone",
        "Magoye",
        "Mapatizya",
        "Mazabuka Central",
        "Mbabala",
        "Monze",
        "Moomba",
        "Namwala",
        "Pemba",
        "Siavonga",
        "Sinazongwe",
    ],
    "Western": [
        "Kalabo Central",
        "Kaoma",
        "Liuwa",
        "Luampa",
        "Luena",
        "Lukulu East",
        "Mangango",
        "Mitete",
        "Mongu Central",
        "Mulobezi",
        "Mwandi",
        "Nalikwanda",
        "Nalolo",
        "Nkeyema",
        "Senanga",
        "Sesheke",
        "Shang’ombo",
        "Sikongo",
        "Sioma",
    ],
}
